config/routes.rb
Rails.application.routes.draw do
  # get 'bookings/index'
  # get 'cars/index'
  # get 'cars/show'
  # get 'cars/new'
  # get 'cars/create'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :cars, only: [:index, :new, :create, :show, :destroy, :edit, :update] do
    resources :bookings, only: [:new, :create]
  end
  resources :bookings, only: [:index, :update]
  get "your_cars", to: "cars#yourcars"
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
end

app/models/car.rb
class Car < ApplicationRecord
  belongs_to :user
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_by_manufacturer_and_model,
    against: [ :manufacturer, :model, :category],
    using: {
      tsearch: { prefix: true }
  }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bookings
  has_many :cars
  has_one_attached :photo
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  add_flash_types :info, :error, :success
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
    # @car = Car.find(params[:id])
    # @bookings = Booking.where(car: @car)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path(@booking)
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @car = Car.find(params[:car_id])
    @booking.user = current_user
    @booking.car = @car
    @booking.save!
    # redirect_to car_bookings_path(@booking.car)
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:total_price, :start_date, :end_date, :user_id, :car_id)
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  def index
    if params[:query].present?
      @cars = Car.search_by_manufacturer_and_model(params[:query])
      if @cars.empty?
        flash.alert = "No cars found matching this search.\nHere are some others."
        @cars = Car.all
      end
    else
      @cars = Car.all
    end
  end

  def show
    @car = Car.find(params[:id])
    @bookings = Booking.where(car: @car)
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.new(car_params)
    # @car = Car.find(params[:car_id])
    @car.user = current_user
    @car.save!
    redirect_to cars_path
  end

  def yourcars
    @cars = current_user.cars
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path, status: :see_other
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    redirect_to cars_path(@car)
  end

  private

  def car_params
    params.require(:car).permit(:manufacturer, :year, :model, :category, :day_price, :user_id, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
 <div class="p-3">
    <h1 id="bookings_title">Your bookings</h1>
    <div data-bs-spy="scroll" data-bs-target="post-module" class="box">
      <%current_user.bookings.each do |booking| %>
        <div id="ernesto-container">
          <!-- booking card-->
          <div class="column">
            <div class="post-module">
              <div class="thumbnail">
                <%# logo card %>
                <div class="img-card">
                    <% if booking.car.photo.key %>
                      <%= cl_image_tag booking.car.photo.key %>
                    <% else%>
                      <img src="https://source.unsplash.com/random/500×300/?car" alt="car" width="600 px">
                    <%end%>
                </div>
              </div>
              <!--Content-->
              <div class="post-content">
                <div class="category"><%=booking.car.model%></div>
                <div class="info-card">
                  <h1 class="title">Your <%=booking.car.manufacturer%> is waiting for you</h1>
                  <p>You can pick up your car on <%=booking.start_date%> and return it on <%=booking.start_date%> </a></p>

                </div>
                <p> £<%=booking.total_price%></p>
                <button class="btn btn-primary">Message <%= booking.car.user.name%></button>
                <%# <p>Please contact <%= booking.car.user.email%>
                <%# <div class="post-meta"><span class="comments"><i class="fa fa-comments"></i><a href="#">39 comments</a></span></div> %>
              </div>
            </div>
          </div>
        </div>
      <%end %>
    </div>
  </div>

app/views/bookings/new.html.erb
<h1> New booking</h2>
  <div class="m-3" data-controller="price">
    <div>
      <%= simple_form_for [@car, @booking] do |f| %>
      <div data-action="change->price#submitDate">
        <%= f.input :start_date, html5: true, input_html: {"data-price-target": "start"} %>
      </div>
      <div data-action="change->price#submitEndDate">
        <%= f.input  :end_date, html5: true, input_html: {data: {target: "end_date"}} %>
      </div>
        <%= f.input :total_price, html5: true, input_html: {"data-price-target": "money", class:"d-none"}, label:false%>
        <%= f.submit "Submit booking", class: "btn btn-primary" %>
      <% end %>
    </div>

<div class="d-none">
  <p >Total days:
    <p id="days">  </p>
  </p>
</div>

 <div class="alert alert-primary" role="alert">
  <div class="h4">
    <p >Price per day:
      £<span data-price-target="daily"><%= @car.day_price %></span>
    </p>
    <p>Total price:
      £ <span id="totalprice"> 0</span>
    </p>
  </div>
</div>


</div>


<%# <h1>
Total price:

  <%= :end_date - :start_date %>

<%# </h1> %>

<%# <h1> Testing
<%=a = Date.parse("12/1/2010") %>
<%# <%=b = Date.parse("12/21/2010") %>
<%# <%=c = b.mjd - a.mjd %>
<%# <h1>  %>

app/views/cars/_car_card.html.erb
<div class="car-card-container">
<%=link_to car_path(car.id), class: "sub-flex-link" do %>
  <% if car.photo.key %>
    <%= cl_image_tag car.photo.key, class:"car-image" %>
  <% else%>
    <img class="car-image" src="https://api.unsplash.com/search/photos/?query=<%=car.manufacturer + " " + car.model%>" alt="car">
  <%end%>

<% end %>
  <div class="sub-flex-text">
    <div class="sub-flex-left">
      <h5><%=car.manufacturer + " " + car.model%></h5>
      <h6><%=car.year%></h6>
      <h6><%=car.category%></h6>
    </div>
    <div class="sub-flex-right">
      <h6>£<%=car.day_price%> per day</h6>

    <%=link_to "Read more", car_path(car.id), class: "sub-flex-link" %>
    </div>
  </div>
</div>

app/views/cars/_carousel.html.erb
<div class="container">
  <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
       <img src=".. https://cdn.sportscardigest.com/wp-content/uploads/20220313154349/10-Greatest-Japanese-Cars-02-Datsun-240Z.jpg" class="d-block w-100" alt="Datsun-240Z"> %>
      <div class="carousel-caption d-none d-md-block">
        <h5>Feel alive</h5>
        <p>Do you want to drive through history?</p>
        <div class="btn-info">
        <p class="btn-show"><%= link_to "show", cars_path(@cars.id) </p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://cdn.sportscardigest.com/wp-content/uploads/20220416134332/Best-Italian-Cars-05-Ferrari-250-GTO.jpg" class="d-block w-100" alt="Ferrari-250-GTO">
      <div class="carousel-caption d-none d-md-block">
        <h5>Travel to the past</h5>
        <div class="btn-info">
          <p class="btn-show"><%= link_to "show", cars_path(@cars.id) </p>
        </div>
        <p>Do you want to drive a legendary car?</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://cdn.sportscardigest.com/wp-content/uploads/20220330111038/01-BMW-328.jpg" class="d-block w-100" alt="BMW-328">
      <div class="carousel-caption d-none d-md-block">
        <h5>Imagine that it is possible</h5>
        <div class="btn-info">
          <p class="btn-show"><%= link_to "show", cars_path(@cars.id) </p>
        </div>
        <p>In classic cars your dreams are on wheels.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
  </div>
</div>

app/views/cars/_carrousel.html.erb
<div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active" data-bs-interval="10000">
      <img src="https://cdn.sportscardigest.com/wp-content/uploads/20220313154349/10-Greatest-Japanese-Cars-02-Datsun-240Z.jpg" class="d-block w-100" alt="Datsun-240Z">
      <div class="carousel-caption d-none d-md-block">
        <h5>Feel alive</h5>
        <p>Do you want to drive through history?</p>
        <div class="btn-info">
        <p class="btn-show"><%= link_to "show", show_cars_path(@cars) %></p>
      </div>
    </div>
    <div class="carousel-item" data-bs-interval="2000">
      <img src="https://cdn.sportscardigest.com/wp-content/uploads/20220416134332/Best-Italian-Cars-05-Ferrari-250-GTO.jpg" class="d-block w-100" alt="Ferrari-250-GTO">
      <div class="carousel-caption d-none d-md-block">
        <h5>Travel to the past</h5>
        <div class="btn-info">
          <p class="btn-show"><%= link_to "show", show_cars_path(@cars) %></p>
        </div>
        <p>Do you want to drive a legendary car?</p>
      </div>
    </div>
    <div class="carousel-item">
      <img src="https://cdn.sportscardigest.com/wp-content/uploads/20220330111038/01-BMW-328.jpg" class="d-block w-100" alt="BMW-328">
      <div class="carousel-caption d-none d-md-block">
        <h5>Imagine that it is possible</h5>
        <div class="btn-info">
          <p class="btn-show"><%= link_to "show", show_cars_path(@cars) %></p>
        </div>
        <p>In classic cars your dreams are on wheels.</p>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/cars/_user_card.html.erb
<div class="user-card-container">
  <% if car.user.photo.valid? %>
    <%= image_tag(car.user.photo, class: "user-avatar")%>
  <% else%>
    <img class="user-avatar" src="https://cdn-icons-png.flaticon.com/512/149/149452.png" alt="user-avatar">
  <%end%>
  <h4 class="user-name"><%= car.user.name %></h4>
  <p class="user-intro">I really love cars, mmmmm cars. Fast ones, old ones, gotta love em.</p>
</div>

app/views/cars/create.html.erb
<h1>Cars#create</h1>
<p>Find me in app/views/cars/create.html.erb</p>

app/views/cars/edit.html.erb
<h2>This is the update page </h2>


  <%= simple_form_for [@car] do |f| %>
    <%= f.input :manufacturer %>
    <%= f.input :year %>
    <%= f.input :model %>
    <%= f.input :category, collection: ["Hatchback", "Saloon", "Estate", "MPV", "SUV", "Coupe", "Sports car", "Convertible"] %>
    <%= f.input :day_price, :label =>"Day Price (£)" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit car", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/index.html.erb
<div class="container p-3">
  <div class="cars-grid">
    <%@cars.each do |car| %>
      <%= render partial: '/cars/car_card', locals: {car: car} %>
    <%end%>
  </div>
</div>

app/views/cars/new.html.erb
<div class="p-3">
 <div style="min-height: calc(100vh - 100px - 56px)">
  <div class="container">
   <div class="form-row d-flex justify-content-center">


  <%= simple_form_for [@car] do |f| %>
    <%= f.input :manufacturer %>
    <%= f.input :year %>
    <%= f.input :model %>
    <%= f.input :category, collection: ["Hatchback", "Saloon", "Estate", "MPV", "SUV", "Coupe", "Sports car", "Convertible"] %>
    <%= f.input :day_price, :label =>"Day Price (£)" %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Submit car", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/cars/show.html.erb
<div class="buttons-container">
  <div class="arrow-box">
    <i class="fa-solid fa-arrow-left"></i>
    <%=link_to "Back to car list", cars_path, class: "btn btn-light"%>
  </div>
  <div class="user-options">
    <%if current_user == @car.user%>
      <%=link_to "Edit this car", edit_car_path, class: "btn btn-light" %>
      <%= link_to "Remove your car listing", car_path(@car), class: "btn btn-light", data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}%>
    <%end%>
  </div>
</div>
<div id="car-page-all">
  <div class="card-trip">
    <% if @car.photo.key %>
      <%= cl_image_tag @car.photo.key %>
    <% else%>
      <img src="https://source.unsplash.com/random/500×300/?car" alt="car" width="600 px">
    <%end%>
  </div>
  <div class="card-trip-infos">
    <p>Make: <%= @car.manufacturer.upcase%></p>
    <p>Model: <%= @car.model %></p>
    <p>Year: <%= @car.year %></p>
    <p>Category: <%= @car.category %></p>
    <p>Daily Price: £<%= @car.day_price %></p>
    <%=link_to "Book this car", new_car_booking_path(@car), class: "btn btn-primary" %>
  </div>
  <div>
    <%= render partial: '/cars/user_card', locals: {car: @car}%>
  </div>
</div>


   <%if current_user == @car.user%>
     <%@bookings.each do |booking| %>
      <ul>
        <li><%=booking.total_price%></li>
        <li><%=booking.start_date%></li>
        <li><%=booking.end_date%></li>
      </ul>
      <%end %>
   <%end%>

app/views/cars/yourcars.html.erb
<div class="container p-3">
  <div class="cars-grid">
    <%@cars.each do |car| %>
      <%= render partial: '/cars/car_card', locals: {car: car} %>
    <%end%>
  </div>
</div>

app/views/layouts/_footer.html.erb
<!-- Footer -->

 <footer class="text-center text-lg-start bg-light text-muted">
  <!-- Section: Links  -->
  <section class="">
    <div class="container text-center text-md-start mt-5">
      <!-- Grid row -->
      <div class="row mt-3">
        <!-- Grid column -->
        <div class="col-md-3 col-lg-4 col-xl-3 mx-auto">
          <!-- Content -->
          <h6 class="text-uppercase fw-bold">
          © 2022 Legend Cars, Inc
          </h6>
          <p>
            We are an online market place for renting primarely classic cars. Based in London, the platform is currently only accesible through our website.
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-2 col-lg-2 col-xl-2 mx-auto">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold">
            Services
          </h6>
          <p>
            <a href="#!" class="text-reset">Find a Car</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Rent your car</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-3 col-lg-2 col-xl-2 mx-auto">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold">
            Useful links
          </h6>
          <p>
            <a href="#!" class="text-reset">Settings</a>
          </p>
          <p>
            <a href="#!" class="text-reset">Help</a>
          </p>
        </div>
        <!-- Grid column -->

        <!-- Grid column -->
        <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0">
          <!-- Links -->
          <h6 class="text-uppercase fw-bold">Contact</h6>
          <p><i class="fas fa-home me-3"></i> 47 Frith St, London W1D 4HT, United Kingdom</p>
          <p>
            <i class="fas fa-envelope me-3"></i>
            info@legendcars.com
          </p>
        </div>
        <!-- Grid column -->
      </div>
      <!-- Grid row -->
    </div>
  </section>


  <!-- Section: Social media -->
  <section class="d-flex justify-content-center p-3 border-bottom">
    <!-- Left -->
      <span class="mx-3">Get connected with us on social networks:</span>
    <!-- Left -->

    <!-- Right -->
    <div>
        <i class="fab fa-facebook-f mx-2"></i>
        <i class="fab fa-twitter mx-2"></i>
        <i class="fab fa-instagram mx-2"></i>
        <i class="fab fa-linkedin mx-2"></i>
        <i class="fab fa-github mx-2"></i>
    </div>
    <!-- Right -->
  </section>
  <!-- Section: Social media -->
</footer>
<!-- Footer -->

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid collapse navbar-collapse" id="navbarSupportedContent">

    <div class="nav-item" id="left-div">
      <%= link_to "/", class: "navbar-brand" do %>
        <%= image_tag "cars_black.png" %>
      <h5 class="logo-font">LEGEND CARS</h5>
      <% end %>
    </div>

    <div class="nav-item">
      <%= form_with url: cars_path, method: :get, class: "rounded d-flex input-group" do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          id: "search-bar",
          placeholder: "Audi Quattro, Jaguar E-Type, Aston Martin DB5",
          autocomplete: "off"
        %>
        <%= submit_tag "Find a car", class: "btn btn-outline-primary", id:"button-search" %>
        <% end %>
    </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
     <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent right-div">
      <div class="nav-item justify-content-end dropdown">
      <div class="dropdown dropdown-toggle d-flex align-items-center pointer"  id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <h6 id="your-account" class="mb-0 p-3">Your Account</h6>
        <%= image_tag "https://cdn-icons-png.flaticon.com/512/149/149452.png", class: "avatar"%>
      </div>
      <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
        <%= link_to "My Profile", user_session_path, class: "dropdown-item" %>
        <%= link_to "Your Bookings", bookings_path, class: "dropdown-item" %>
        <%= link_to "Your Cars", your_cars_path, class: "dropdown-item" %>
        <%= link_to "Rent out your car", new_car_path, class: "dropdown-item" %>
      </div>
      </div>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ClassicCarsApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <%# for bookings_index %>
    <script src="//use.typekit.net/xyl8bgh.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
  </head>

  <body>
  <div class="d-flex flex-column min-vh-100">
    <%= render partial: '/layouts/navbar' %>
    <article class="flex-grow-1">
    <%= render partial: '/shared/flashes' %>
    <%= yield %>
    </article>
    <%= render partial: '/layouts/footer' %>
  </div>
  </body>
</html>

app/views/pages/home.html.erb
<div id="container">
  <div id="carouselExampleDark" class="carousel carousel-dark slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
  <div class="carousel-inner">

    <div class="carousel-item active" data-bs-interval="10000">
      <img class= "img-carousel d-block w-100" src="https://cdn.luxe.digital/media/2021/11/26104812/best-classic-cars-vintage-Aston-Martin-DB5-1964-old-luxe-digital%402x.jpg" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="title-carousel">FEEL ALIVE</h1>
        <h2 class="description-carousel">Do you want to drive through history?</h2>
      </div>
    </div>

    <div class="carousel-item" data-bs-interval="2000">
      <img class= "img-carousel d-block w-100" src="https://www.motorbiscuit.com/wp-content/uploads/2021/06/Classic-Car-on-display-1024x683.jpg" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="title-carousel">TRAVEL TO THE PAST</h1>
        <h2 class="description-carousel">Do you want to drive a legendary car?</h2>
      </div>
    </div>

    <div class="carousel-item">
      <img class= "img-carousel d-block w-100" src="https://m.atcdn.co.uk/ect/media/%7Bresize%7D/094b59ec1182463fa9cff88df88de65b.jpg" alt="">
      <div class="carousel-caption d-none d-md-block">
        <h1 class="title-carousel">MAKE YOUR DREAMS COME TRUE</h1>
        <h2 class="description-carousel">In classic cars your dreams are on wheels</h2>
      </div>
    </div>

  </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>